#!/usr/bin/env bash
# Lock screen: i3lock-color (bootstrap 5.0) over a random wallpaper, indicator
# colours from ~/.config/i3lock/current.conf (generated by bin/theme.sh, so the
# lock follows the light/dark mode). Used by xss-lock and the bar's lock icon.
# i3lock-color installs as "i3lock"; look in the from-source prefixes first so a
# plain packaged /usr/bin/i3lock (which lacks the colour flags) can't shadow it.
export PATH="$HOME/.local/bin:/usr/local/bin:$PATH"

C="${XDG_CONFIG_HOME:-$HOME/.config}/i3lock"
# shellcheck source=/dev/null
source "$C/current.conf" 2>/dev/null || source "$C/rose-pine.conf"

IMG="$(find ~/Pictures/wallpapers -type f \( -iname '*.jpg' -o -iname '*.png' \) | shuf -n1)"

args=(
  --nofork --show-failed-attempts --ignore-empty-password
  --indicator --radius=110 --ring-width=8
  --clock --time-str="%H:%M" --date-str="%A, %d.%m.%Y"
  --time-font="Cantarell" --date-font="Cantarell" --verif-font="Cantarell" --wrong-font="Cantarell"
  --time-size=34 --date-size=14
  --verif-text="…" --wrong-text="✗" --noinput-text="" --lock-text="" --lockfailed-text="✗"
  --inside-color="$LOCK_INSIDE" --insidever-color="$LOCK_INSIDE_VER" --insidewrong-color="$LOCK_INSIDE_WRONG"
  --ring-color="$LOCK_RING"     --ringver-color="$LOCK_RING_VER"     --ringwrong-color="$LOCK_RING_WRONG"
  --line-uses-ring --separator-color="$LOCK_SEPARATOR"
  --keyhl-color="$LOCK_KEYHL" --bshl-color="$LOCK_BSHL"
  --time-color="$LOCK_TEXT" --date-color="$LOCK_TEXT" --verif-color="$LOCK_TEXT" --wrong-color="$LOCK_TEXT"
  --layout-color="$LOCK_SUBTLE" --greeter-color="$LOCK_SUBTLE" --modif-color="$LOCK_SUBTLE"
)
if [[ -n "$IMG" ]]; then
  args+=(--image="$IMG" --fill)
else
  args+=(--color="$LOCK_BG")
fi
exec i3lock "${args[@]}"
